# Generated by Django 5.2.8 on 2025-12-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DNASequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.CharField(max_length=5000)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('length', models.IntegerField(default=0)),
                ('gc_content', models.FloatField(default=0.0)),
            ],
        ),
    ]
