# Generated by Django 5.2.8 on 2025-12-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnasequence',
            name='length',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dnasequence',
            name='sequence',
            field=models.TextField(max_length=5000),
        ),
    ]
